
services:
  db:
    container_name: project_one_bd
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgAdmin:
    container_name: project_one_pg
    image: dpage/pgadmin4
    restart: always 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
      
